// 16 Chance cards. Effects are interpreted by engine/cards.js.

export const CHANCE_CARDS = [
  { id: 'CH01', text: 'Advance to GO. (Collect $200)',
    effect: { kind: 'moveTo', target: 0, collectGo: true } },
  { id: 'CH02', text: 'Advance to Illinois Avenue. If you pass GO, collect $200.',
    effect: { kind: 'moveTo', target: 24, collectGo: true } },
  { id: 'CH03', text: 'Advance to St. Charles Place. If you pass GO, collect $200.',
    effect: { kind: 'moveTo', target: 11, collectGo: true } },
  { id: 'CH04', text: 'Advance to nearest Utility. If unowned, you may buy it. If owned, throw dice and pay 10x amount.',
    effect: { kind: 'moveToNearestUtility' } },
  { id: 'CH05', text: 'Advance to nearest Railroad. If unowned, you may buy it. If owned, pay 2x rent.',
    effect: { kind: 'moveToNearestRailroad' } },
  { id: 'CH06', text: 'Advance to nearest Railroad. If unowned, you may buy it. If owned, pay 2x rent.',
    effect: { kind: 'moveToNearestRailroad' } },
  { id: 'CH07', text: 'Bank pays you dividend of $50.',
    effect: { kind: 'collect', amount: 50 } },
  { id: 'CH08', text: 'Get Out of Jail Free. This card may be kept until needed.',
    effect: { kind: 'getOutOfJailFree', deck: 'chance' } },
  { id: 'CH09', text: 'Go back 3 spaces.',
    effect: { kind: 'move', steps: -3 } },
  { id: 'CH10', text: 'Go directly to Jail. Do not pass GO. Do not collect $200.',
    effect: { kind: 'goToJail' } },
  { id: 'CH11', text: 'Make general repairs on all your property: $25 per house, $100 per hotel.',
    effect: { kind: 'repairs', perHouse: 25, perHotel: 100 } },
  { id: 'CH12', text: 'Speeding fine. Pay $15.',
    effect: { kind: 'pay', amount: 15 } },
  { id: 'CH13', text: 'Take a trip to Reading Railroad. If you pass GO, collect $200.',
    effect: { kind: 'moveTo', target: 5, collectGo: true } },
  { id: 'CH14', text: 'Take a walk on the Boardwalk. Advance to Boardwalk.',
    effect: { kind: 'moveTo', target: 39, collectGo: true } },
  { id: 'CH15', text: 'You have been elected Chairman of the Board. Pay each player $50.',
    effect: { kind: 'payEachPlayer', amount: 50 } },
  { id: 'CH16', text: 'Your building loan matures. Collect $150.',
    effect: { kind: 'collect', amount: 150 } }
];
