// 16 Community Chest cards.

export const COMMUNITY_CHEST_CARDS = [
  { id: 'CC01', text: 'Advance to GO. (Collect $200)',
    effect: { kind: 'moveTo', target: 0, collectGo: true } },
  { id: 'CC02', text: 'Bank error in your favor. Collect $200.',
    effect: { kind: 'collect', amount: 200 } },
  { id: 'CC03', text: "Doctor's fee. Pay $50.",
    effect: { kind: 'pay', amount: 50 } },
  { id: 'CC04', text: 'From sale of stock you get $50.',
    effect: { kind: 'collect', amount: 50 } },
  { id: 'CC05', text: 'Get Out of Jail Free. This card may be kept until needed.',
    effect: { kind: 'getOutOfJailFree', deck: 'communityChest' } },
  { id: 'CC06', text: 'Go directly to Jail. Do not pass GO. Do not collect $200.',
    effect: { kind: 'goToJail' } },
  { id: 'CC07', text: 'Holiday Fund matures. Receive $100.',
    effect: { kind: 'collect', amount: 100 } },
  { id: 'CC08', text: 'Income tax refund. Collect $20.',
    effect: { kind: 'collect', amount: 20 } },
  { id: 'CC09', text: 'It is your birthday. Collect $10 from each player.',
    effect: { kind: 'collectFromEachPlayer', amount: 10 } },
  { id: 'CC10', text: 'Life insurance matures. Collect $100.',
    effect: { kind: 'collect', amount: 100 } },
  { id: 'CC11', text: 'Hospital fees. Pay $100.',
    effect: { kind: 'pay', amount: 100 } },
  { id: 'CC12', text: 'School fees. Pay $50.',
    effect: { kind: 'pay', amount: 50 } },
  { id: 'CC13', text: 'Receive $25 consultancy fee.',
    effect: { kind: 'collect', amount: 25 } },
  { id: 'CC14', text: 'You are assessed for street repair. $40 per house, $115 per hotel.',
    effect: { kind: 'repairs', perHouse: 40, perHotel: 115 } },
  { id: 'CC15', text: 'You have won second prize in a beauty contest. Collect $10.',
    effect: { kind: 'collect', amount: 10 } },
  { id: 'CC16', text: 'You inherit $100.',
    effect: { kind: 'collect', amount: 100 } }
];
